<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Chino Chang</Authors>
    <Description>Schemata Application Framework - Domain Skeleton</Description>
    <PackageTags>application;business;framework;ddd;domain;aggregate</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Schemata.Abstractions\Schemata.Abstractions.csproj" />
    <ProjectReference Include="..\Schemata.Event.Skeleton\Schemata.Event.Skeleton.csproj" />
  </ItemGroup>

</Project>
