<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Chino Chang</Authors>
    <Description>Schemata Application Framework - Actor Scheduling Integration</Description>
    <PackageTags>application;business;framework;actor;scheduling;reminder</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Schemata.Actor.Foundation\Schemata.Actor.Foundation.csproj" />
    <ProjectReference Include="..\Schemata.Core\Schemata.Core.csproj" />
    <ProjectReference Include="..\Schemata.Scheduling.Foundation\Schemata.Scheduling.Foundation.csproj" />
  </ItemGroup>

</Project>
