namespace Schemata.Flow.Skeleton.Runtime;

/// <summary>
///     One external-effect intent as seen by <see cref="IFlowEffectRecorder" />: the engine records the
///     intent before the task body runs, then settles the same record to <see cref="FlowEffectState.Completed" />
///     or <see cref="FlowEffectState.OutcomeUnknown" />.
/// </summary>
public sealed class FlowEffectIntent
{
    /// <summary>
    ///     Stable request identifier generated by the engine for this task instance. The handler forwards it
    ///     to the external system as that system's idempotency/request id; a re-driven transition reproduces
    ///     the same value.
    /// </summary>
    public required string RequestId { get; init; }

    /// <summary>Canonical name of the process instance that owns the effect.</summary>
    public required string Process { get; init; }

    /// <summary>Canonical name of the token performing the effect.</summary>
    public required string Token { get; init; }

    /// <summary>Name of the task element whose body performs the effect.</summary>
    public required string Task { get; init; }

    /// <summary>Lifecycle state of the record.</summary>
    public FlowEffectState State { get; set; } = FlowEffectState.Recorded;
}
