<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Moq" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Schemata.Entity.EntityFrameworkCore\Schemata.Entity.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Schemata.Authorization.Foundation\Schemata.Authorization.Foundation.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Authorization.Identity\Schemata.Authorization.Identity.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Authorization.Grpc\Schemata.Authorization.Grpc.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Authorization.Http\Schemata.Authorization.Http.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Resource.Foundation\Schemata.Resource.Foundation.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Scheduling.Foundation\Schemata.Scheduling.Foundation.csproj" />
  </ItemGroup>

</Project>
