<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Schemata.Tenancy.Foundation\Schemata.Tenancy.Foundation.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Tenancy.Skeleton\Schemata.Tenancy.Skeleton.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Tenancy.Messaging\Schemata.Tenancy.Messaging.csproj" />
  </ItemGroup>

</Project>
