<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Schemata.Identity.Foundation\Schemata.Identity.Foundation.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Messaging.Skeleton\Schemata.Messaging.Skeleton.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Identity.Grpc\Schemata.Identity.Grpc.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Identity.Http\Schemata.Identity.Http.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Resource.Foundation\Schemata.Resource.Foundation.csproj" />
  </ItemGroup>

</Project>
