using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Schemata.Abstractions.Entities;
using Schemata.Abstractions.Resource;
using Schemata.Flow.Skeleton.Entities;
using Schemata.Flow.Skeleton.Runtime;

namespace Schemata.Flow.Repository;

/// <summary>
///     Durable external-effect intent row written by <see cref="RepositoryFlowEffectRecorder" />. Its
///     purpose is framework-internal reliable execution: the row commits with the flow transition that
///     performed the effect and disappears when that transition rolls back, and <see cref="RequestId" />
///     is the stable identifier the application task handler forwarded to the external system.
/// </summary>
[Table("SchemataFlowEffectIntents")]
[PrimaryKey(nameof(Uid))]
[Index(nameof(RequestId), IsUnique = true)]
[Index(nameof(Token))]
public class SchemataFlowEffectIntent : IIdentifier, IConcurrency, ITimestamp
{
    /// <summary>
    ///     Stable request identifier generated by the engine for the task instance, in the form
    ///     <c>{token canonical name}/effects/{ordinal}</c>. A re-driven transition reproduces the same
    ///     value, so the external system can answer an outcome query or deduplicate a re-issue by it.
    /// </summary>
    public virtual string RequestId { get; set; } = null!;

    /// <summary>Canonical name of the process instance that owns the effect.</summary>
    [ResourceReference(typeof(SchemataProcess))]
    public virtual string Process { get; set; } = null!;

    /// <summary>Canonical name of the token performing the effect.</summary>
    [ResourceReference(typeof(SchemataProcessToken))]
    public virtual string Token { get; set; } = null!;

    /// <summary>Name of the task element whose body performs the effect.</summary>
    public virtual string Task { get; set; } = null!;

    /// <summary>Lifecycle state of the record.</summary>
    public virtual FlowEffectState State { get; set; }

    #region IConcurrency Members

    [ConcurrencyCheck]
    public virtual Guid Timestamp { get; set; }

    #endregion

    #region IIdentifier Members

    public virtual Guid Uid { get; set; }

    #endregion

    #region ITimestamp Members

    public virtual DateTime? CreateTime { get; set; }

    public virtual DateTime? UpdateTime { get; set; }

    #endregion
}
