<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Chino Chang</Authors>
    <Description>Schemata Application Framework - Flow Repository Effect Recorder</Description>
    <PackageTags>application;business;framework;flow;workflow</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Schemata.Entity.Repository\Schemata.Entity.Repository.csproj" />
    <ProjectReference Include="..\Schemata.Flow.Skeleton\Schemata.Flow.Skeleton.csproj" />
  </ItemGroup>

</Project>
