<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFrameworks>net8.0;net10.0</TargetFrameworks></PropertyGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" /><PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" /><PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" /></ItemGroup>
  <ItemGroup><PackageReference Include="Moq" /><PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Schemata.Tenancy.Messaging/Schemata.Tenancy.Messaging.csproj" />
    <ProjectReference Include="../../src/Schemata.Tenancy.Caching/Schemata.Tenancy.Caching.csproj" />
    <ProjectReference Include="../../src/Schemata.Caching.Memory/Schemata.Caching.Memory.csproj" />
    <ProjectReference Include="../../src/Schemata.Actor.Foundation/Schemata.Actor.Foundation.csproj" />
    <ProjectReference Include="../../src/Schemata.Scheduling.Foundation/Schemata.Scheduling.Foundation.csproj" />
    <ProjectReference Include="../../src/Schemata.Scheduling.Repository/Schemata.Scheduling.Repository.csproj" />
    <ProjectReference Include="../../src/Schemata.Actor.Scheduling/Schemata.Actor.Scheduling.csproj" />
    <ProjectReference Include="../../src/Schemata.Event.RabbitMq/Schemata.Event.RabbitMq.csproj" />
    <ProjectReference Include="../../src/Schemata.Event.Foundation/Schemata.Event.Foundation.csproj" />
    <ProjectReference Include="../../src/Schemata.Messaging.RabbitMq/Schemata.Messaging.RabbitMq.csproj" />
    <ProjectReference Include="../../src/Schemata.Entity.EntityFrameworkCore/Schemata.Entity.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../../src/Schemata.Entity.LinqToDB/Schemata.Entity.LinqToDB.csproj" />
    <ProjectReference Include="../../src/Schemata.Transport.Http/Schemata.Transport.Http.csproj" />
  </ItemGroup>
</Project>
