<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="SQLitePCLRaw.core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Schemata.Abstractions\Schemata.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Actor.Foundation\Schemata.Actor.Foundation.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Actor.Skeleton\Schemata.Actor.Skeleton.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Core\Schemata.Core.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Entity.EntityFrameworkCore\Schemata.Entity.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Entity.Repository\Schemata.Entity.Repository.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Flow.Actor\Schemata.Flow.Actor.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Flow.Foundation\Schemata.Flow.Foundation.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Flow.Skeleton\Schemata.Flow.Skeleton.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Flow.StateMachine\Schemata.Flow.StateMachine.csproj" />
    <ProjectReference Include="..\..\src\Schemata.Messaging.Skeleton\Schemata.Messaging.Skeleton.csproj" />
  </ItemGroup>

</Project>
