<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Chino Chang</Authors>
    <Description>Schemata Application Framework - Report Actor Integration</Description>
    <PackageTags>application;business;framework;report;snapshot;actor</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Schemata.Actor.Foundation\Schemata.Actor.Foundation.csproj" />
    <ProjectReference Include="..\Schemata.Report.Foundation\Schemata.Report.Foundation.csproj" />
  </ItemGroup>

</Project>